// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxfd9hJ0NYN9KNP6UdCTU5VWHGLum-VFE',
    appId: '1:463313212619:web:29b6ae18f4648e6ae1774e',
    messagingSenderId: '463313212619',
    projectId: 'allowance-001',
    authDomain: 'allowance-001.firebaseapp.com',
    storageBucket: 'allowance-001.firebasestorage.app',
    measurementId: 'G-1K8Q2V9G2Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgek7qSHlKs6-0CqGvqxJt3gPEesaboEA',
    appId: '1:463313212619:ios:8e765df639570cdce1774e',
    messagingSenderId: '463313212619',
    projectId: 'allowance-001',
    storageBucket: 'allowance-001.firebasestorage.app',
    iosBundleId: 'com.example.allowance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxfd9hJ0NYN9KNP6UdCTU5VWHGLum-VFE',
    appId: '1:463313212619:web:fdec4665ef8d1e5de1774e',
    messagingSenderId: '463313212619',
    projectId: 'allowance-001',
    authDomain: 'allowance-001.firebaseapp.com',
    storageBucket: 'allowance-001.firebasestorage.app',
    measurementId: 'G-ZK8SC59LKK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgek7qSHlKs6-0CqGvqxJt3gPEesaboEA',
    appId: '1:463313212619:ios:8e765df639570cdce1774e',
    messagingSenderId: '463313212619',
    projectId: 'allowance-001',
    storageBucket: 'allowance-001.firebasestorage.app',
    iosBundleId: 'com.example.allowance',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCao3dUq_2lDzW6NuX6GhDYnVguiR-mr8k',
    appId: '1:463313212619:android:4d7666b9e46aaa3ce1774e',
    messagingSenderId: '463313212619',
    projectId: 'allowance-001',
    storageBucket: 'allowance-001.firebasestorage.app',
  );
}
